<a href="https://colab.research.google.com/github/koko11-11/ML-AutoML/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
arr_1=[1,2,3,4,5]
#2d
np_arr_1=np.array(arr_1,dtype=np.int8)
np_arr_1

array([1, 2, 3, 4, 5], dtype=int8)

In [4]:
multi_arr=[[1,2,3],[4,5,6],[7,8,9]]
#2d
np_multi_arr=np.array(multi_arr)
np_multi_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
multi_arr2=[[[1.5,2,3],[4,5,6]],[[3,2,1],[4,5,6]]]
#3d
np_multi_arr2=np.array(multi_arr2)
np_multi_arr2

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [6]:
np.arange(1,10)


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.linspace(0,5,7)

array([0.        , 0.83333333, 1.66666667, 2.5       , 3.33333333,
       4.16666667, 5.        ])

In [9]:
np.zeros(4) #1d

array([0., 0., 0., 0.])

In [10]:
np.zeros((2,3)) #2d 2*3 matrix of zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones((3,4)) #same thing

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.eye(3,3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [13]:
np_multi_arr.size

9

In [14]:
np_multi_arr.dtype

dtype('int64')

In [15]:
np_multi_arr2.dtype

dtype('float64')

In [16]:
np.random.randint(10,50,7)

array([15, 12, 43, 47, 23, 36, 42])

In [17]:
np.random.randint(10,50,size=(2, 3))

array([[22, 13, 34],
       [25, 24, 43]])

In [18]:
multi_arr=[[1,2,3],[4,5,6],[7,8,9]]
np_multi_arr=np.array(multi_arr)
np_multi_arr,np_multi_arr.shape

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 (3, 3))

In [20]:
np_multi_arr[0,2]

np.int64(3)

In [21]:
np_multi_arr(0,2) #u can't use just ()

TypeError: 'numpy.ndarray' object is not callable

In [22]:
np_multi_arr.item(0,2)

3

In [25]:
np.take(np_multi_arr,[0,2,4,8])

array([1, 3, 5, 9])

In [26]:
np_arr_1[3:5]

array([4, 5], dtype=int8)

In [27]:
np_arr_1[:4]

array([1, 2, 3, 4], dtype=int8)

In [28]:
np_arr_1[::-1]

array([5, 4, 3, 2, 1], dtype=int8)

In [29]:
np_arr_1

array([1, 2, 3, 4, 5], dtype=int8)

In [30]:
np_multi_arr[:,0] #first column from all

array([1, 4, 7])

In [31]:
np_multi_arr[0,:]

array([1, 2, 3])

In [32]:
np_multi_arr[np_multi_arr>4]

array([5, 6, 7, 8, 9])

In [33]:
np_multi_arr[(np_multi_arr>4)&(np_multi_arr<8)]

array([5, 6, 7])

In [34]:
np.put(np_multi_arr,[0,3,5],[2,2,2]) #inplace

In [35]:
np_multi_arr

array([[2, 2, 3],
       [2, 5, 2],
       [7, 8, 9]])

In [36]:
np.unique(np_multi_arr)

array([2, 3, 5, 7, 8, 9])